### ISSUE TITLE
No way to tell if connected (received 001)

### ISSUE THREAD

**Issue by causal-agent** [Raynes/irclj#4]
There is no way to tell if the bot is connected and able to send joins, messages, etc. (received 001)

**Comment by Raynes** [comment]
Got rid of the redundant when-not-nil function since plain 'ol when works just fine for now. Added some stuff so that we can handle 001 a little differently. There is a handler now, and after 001 is recieved, it sets :connected? to true. The handler also triggers an :on-connect callback if one exists. Closed by 1d7b28297ecf00f275641af49b44090a1bcd8ed8. Closed by 1d7b28297ecf00f275641af49b44090a1bcd8ed8.
